### ISSUE TITLE
ETH RPC test cases are failing while doing `make test-rpc`

### ISSUE THREAD

**Issue by gsk967** [vulcanize/chiba-clonk#37]
Branch : `sai/upgrade_cosmos_v0.46`

1. Clone the repo 
2. Checkout to branch `sai/upgrade_cosmos_v0.46`
3. Run `make test-rpc`

```=== RUN   TestEth_Pending_GetTransactionCount
    rpc_pending_test.go:97: Pending nonce before tx is 1
    rpc_pending_test.go:100: Current nonce is 1
    utils.go:92: 
        	Error Trace:	utils.go:92
        	            				rpc_pending_test.go:104
        	Error:      	Expected nil, but got: &rpc.Error{Code:-32000, Message:"no registered implementations of type tx.TxExtensionOptionI: tx parse error: tx parse error", Data:interface {}(nil)}
        	Test:       	TestEth_Pending_GetTransactionCount
--- FAIL: TestEth_Pending_GetTransactionCount (6.09s)
```

Please check errors on [github actions](https://github.com/vulcanize/chiba-clonk/runs/6222622907?check_suite_focus=true#step:5:363)

**Comment by i-norden** [comment]
Here is where that error msg originates from: https://github.com/cosmos/cosmos-sdk/blob/main/codec/types/interface_registry.go#L224.

So, I’m not sure how or why yet, but I think we need to register the `tx.TxExtensionOptionI` type with the interface registry with either https://github.com/cosmos/cosmos-sdk/blob/main/codec/types/interface_registry.go#L112 or https://github.com/cosmos/cosmos-sdk/blob/main/codec/types/interface_registry.go#L124.

I think we need to do that in the app.go somewhere https://github.com/vulcanize/chiba-clonk/blob/main/app/app.go#L212.

Somewhere between https://github.com/vulcanize/chiba-clonk/blob/main/app/app.go#L278 and https://github.com/vulcanize/chiba-clonk/blob/main/app/app.go#L290 I suspect.

Not sure where this `tx.TxExtensionOptionI` type comes from yet.

Or how exactly to register it with either of those methods.

I believe we use https://github.com/cosmos/cosmos-sdk/blob/main/codec/types/interface_registry.go#L112, the tx.TxExtensionOptionI is provided as the first arg, but not sure what the implementation arg (proto message type) is yet.

**Comment by roysc** [comment]
I registered `ExtensionOptionsEthereumTx` as a `TxExtensionOptionI` implementation, which has appeased the middleware for long enough to expose some separate issues: first with Tx decoding, which I fixed by refactoring the middleware. Now, the gas limit is being hit on the evm keeper's param store, triggering a panic.

WIP at https://github.com/vulcanize/chiba-clonk/pull/39.
