### ISSUE TITLE
Replace go-ipld-cbor codec with go-ipld-prime version

### ISSUE THREAD

**Issue by i-norden** [vulcanize/chiba-clonk#40]
Currently we use the [old go-ipld-cbor codec](https://github.com/vulcanize/chiba-clonk/blob/main/go.mod#L23), we should upgrade to using the go-ipld-prime interfaces and the corresponding dag-cbor codec: https://github.com/ipld/go-ipld-prime/tree/master/codec/dagcbor. This will enable forward compatibility with any other codec that conforms to the go-ipld-prime interfaces.

**Comment by ashwinphatak** [comment]
Also check if there is a compatible client (TypeScript) library.

**Comment by i-norden** [comment]
@ashwinphatak for dag-cbor there is: https://github.com/ipld/js-dag-cbor but there isn't a go-ipld-prime analog for JS/TS, all the codecs are still standalone repos.

**Comment by i-norden** [comment]
We need to replace usage here as well: https://github.com/vulcanize/chiba-clonk/blob/main/x/nameservice/helpers/helpers.go#L11
