### ISSUE TITLE
v0.46-SMT (post-middleware revsion) compatible chiba-clonk

### ISSUE THREAD

**Issue by i-norden** [vulcanize/chiba-clonk#46]
- [x] Refactor/rebase our SMT branch of the SDK on-top of the new nascent v0.46 release that includes the reversion to using antehandlers instead of middleware
- [ ] Refactor chiba-clonk to use a release of the above

**Comment by roysc** [comment]
The [working branch of the SDK](https://github.com/vulcanize/cosmos-sdk/tree/release-v0.46.0-smt-0.0.3-alpha) has been updated with the refactor.

**Comment by gsk967** [comment]
Started working on 2nd Sub Issue (Refactor chiba-clonk to use a release of the cosmos-sdk)
